"""
alert_store.py — SQLite/Postgres-backed alert store for Argus UEBA.

Alerts are auto-generated by the /ingest pipeline when anomaly thresholds
are crossed, and can be acknowledged / resolved by SOC analysts.

Schema
------
alerts:
    id          — auto-increment PK
    user_id     — the flagged user
    alert_type  — 'rarity_spike' | 'ae_critical' | 'anomalous_behavior' | 'new_user'
    severity    — 'Critical' | 'High' | 'Medium' | 'Low'
    title       — human-readable summary (shown in the UI)
    details     — JSON object with context (scores, flags fired, etc.)
    status      — 'Open' | 'Acknowledged' | 'Resolved' | 'False Positive'
    created_at  — ISO 8601 timestamp
    resolved_at — ISO 8601 timestamp or NULL

Deduplication
-------------
`recent_alert_exists()` prevents creating the same alert type for the same
user more than once per hour, so a single bursty ingest session doesn't
flood the queue with hundreds of identical alerts.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any

# Re-use connection helpers from event_store (same database, same backend)
from backend.event_store import _PG, _cursor, _db, _rows, _PH  # noqa: PLC2701

# ---------------------------------------------------------------------------
# DDL
# ---------------------------------------------------------------------------

_DDL_ALERTS = """
    CREATE TABLE IF NOT EXISTS alerts (
        id          {pk},
        user_id     TEXT    NOT NULL,
        alert_type  TEXT    NOT NULL,
        severity    TEXT    NOT NULL DEFAULT 'High',
        title       TEXT    NOT NULL,
        details     TEXT    DEFAULT '{{}}',
        status      TEXT    NOT NULL DEFAULT 'Open',
        created_at  TEXT    NOT NULL,
        resolved_at TEXT
    )
""".format(pk="BIGSERIAL PRIMARY KEY" if _PG else "INTEGER PRIMARY KEY AUTOINCREMENT")


# ---------------------------------------------------------------------------
# Schema init (called once at startup from main.py)
# ---------------------------------------------------------------------------

def init_alerts_db() -> None:
    """Create the alerts table and indices if they don't exist."""
    with _db() as con:
        cur = _cursor(con)
        cur.execute(_DDL_ALERTS)
        cur.execute("CREATE INDEX IF NOT EXISTS idx_al_user   ON alerts(user_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_al_status ON alerts(status)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_al_ts     ON alerts(created_at)")


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

def create_alert(
    user_id:    str,
    alert_type: str,
    severity:   str,
    title:      str,
    details:    dict | None = None,
) -> dict[str, Any]:
    """Insert a new Open alert and return the created row as a dict."""
    now          = datetime.now(timezone.utc).isoformat()
    details_json = json.dumps(details or {})

    with _db() as con:
        cur = _cursor(con)
        cur.execute(
            f"""
            INSERT INTO alerts (user_id, alert_type, severity, title, details, status, created_at)
            VALUES ({_PH}, {_PH}, {_PH}, {_PH}, {_PH}, 'Open', {_PH})
            """,
            (user_id, alert_type, severity, title, details_json, now),
        )
        # Retrieve the just-inserted row
        if _PG:
            cur.execute(
                f"SELECT * FROM alerts WHERE user_id = {_PH} AND created_at = {_PH}",
                (user_id, now),
            )
        else:
            cur.execute("SELECT * FROM alerts WHERE rowid = last_insert_rowid()")
        rows = _rows(cur)

    return _parse(rows[0]) if rows else {}


def update_status(alert_id: int, status: str) -> dict[str, Any] | None:
    """
    Update an alert's status and return the updated row.

    Setting status to 'Resolved' or 'False Positive' also fills in resolved_at.
    Returns None if *alert_id* does not exist.
    """
    now         = datetime.now(timezone.utc).isoformat()
    is_terminal = status in {"Resolved", "False Positive"}

    with _db() as con:
        cur = _cursor(con)
        if is_terminal:
            cur.execute(
                f"UPDATE alerts SET status = {_PH}, resolved_at = {_PH} WHERE id = {_PH}",
                (status, now, alert_id),
            )
        else:
            cur.execute(
                f"UPDATE alerts SET status = {_PH}, resolved_at = NULL WHERE id = {_PH}",
                (status, alert_id),
            )
        cur.execute(f"SELECT * FROM alerts WHERE id = {_PH}", (alert_id,))
        rows = _rows(cur)

    return _parse(rows[0]) if rows else None


def get_alert(alert_id: int) -> dict[str, Any] | None:
    """Return a single alert by id, or None."""
    with _db() as con:
        cur = _cursor(con)
        cur.execute(f"SELECT * FROM alerts WHERE id = {_PH}", (alert_id,))
        rows = _rows(cur)
    return _parse(rows[0]) if rows else None


def purge_all() -> int:
    """Delete every alert. Returns the number removed."""
    with _db() as con:
        cur = _cursor(con)
        cur.execute("SELECT COUNT(*) AS c FROM alerts")
        n = int(dict(cur.fetchone()).get("c", 0))
        cur.execute("DELETE FROM alerts")
    return n


def bulk_create(alerts: list[dict[str, Any]]) -> int:
    """Insert many Open alerts in one transaction (no per-row SELECT-back)."""
    now = datetime.now(timezone.utc).isoformat()
    with _db() as con:
        cur = _cursor(con)
        for a in alerts:
            cur.execute(
                f"""
                INSERT INTO alerts (user_id, alert_type, severity, title, details, status, created_at)
                VALUES ({_PH}, {_PH}, {_PH}, {_PH}, {_PH}, 'Open', {_PH})
                """,
                (a["user_id"], a["alert_type"], a["severity"], a["title"],
                 json.dumps(a.get("details", {})), now),
            )
    return len(alerts)


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------

def list_alerts(
    status: str | None = None,
    limit:  int        = 50,
    offset: int        = 0,
) -> list[dict[str, Any]]:
    """Return alerts ordered newest first, optionally filtered by *status*."""
    with _db() as con:
        cur = _cursor(con)
        if status:
            cur.execute(
                f"""
                SELECT * FROM alerts
                WHERE  status = {_PH}
                ORDER  BY created_at DESC
                LIMIT  {_PH} OFFSET {_PH}
                """,
                (status, limit, offset),
            )
        else:
            cur.execute(
                f"""
                SELECT * FROM alerts
                ORDER  BY created_at DESC
                LIMIT  {_PH} OFFSET {_PH}
                """,
                (limit, offset),
            )
        rows = _rows(cur)

    return [_parse(r) for r in rows]


def get_stats() -> dict[str, int]:
    """Return counts of alerts grouped by status."""
    with _db() as con:
        cur = _cursor(con)
        cur.execute("SELECT status, COUNT(*) AS cnt FROM alerts GROUP BY status")
        rows = _rows(cur)

    counts = {r["status"]: int(r["cnt"]) for r in rows}
    return {
        "open":           counts.get("Open", 0),
        "acknowledged":   counts.get("Acknowledged", 0),
        "resolved":       counts.get("Resolved", 0),
        "false_positive": counts.get("False Positive", 0),
        "total":          sum(counts.values()),
    }


def recent_alert_exists(user_id: str, alert_type: str, minutes: int = 60) -> bool:
    """
    Return True if an Open or Acknowledged alert of *alert_type* already
    exists for *user_id* within the last *minutes* minutes.

    Used by the ingest pipeline to suppress duplicate alert creation.
    """
    since = (datetime.now(timezone.utc) - timedelta(minutes=minutes)).isoformat()
    with _db() as con:
        cur = _cursor(con)
        cur.execute(
            f"""
            SELECT COUNT(*) AS cnt FROM alerts
            WHERE  user_id    = {_PH}
              AND  alert_type = {_PH}
              AND  status     IN ('Open', 'Acknowledged')
              AND  created_at >= {_PH}
            """,
            (str(user_id), alert_type, since),
        )
        row = cur.fetchone()

    return int(dict(row).get("cnt", 0)) > 0


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _parse(row: dict) -> dict:
    """Parse the details JSON string to a dict in the row."""
    if isinstance(row.get("details"), str):
        try:
            row["details"] = json.loads(row["details"])
        except Exception:  # noqa: BLE001
            row["details"] = {}
    return row
